import Image from 'next/image'
import { ArrowDown, ArrowUpRight, Flame, Utensils } from 'lucide-react'
import { LocationSection } from '@/components/location-section'

function Brand({ light = false }: { light?: boolean }) {
  return <a href="#top" className={`flex items-center gap-3 ${light ? 'text-background' : 'text-foreground'}`}><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Captura%20de%20Tela%202026-09-03%20a%CC%80s%2000.43.23-d1OzOUNNxrhILiS7fgg8hDpp5JhvN0.png" alt="The King of Picanha logo" width={180} height={72} className={`h-16 w-auto object-contain ${light ? '' : 'brightness-75'}`} /></a>
}

export default function Page() {
  return <main>
    <section id="top" className="relative min-h-[100svh] overflow-hidden bg-foreground text-background">
      <Image src="/images/hero-picanha.png" alt="Sliced picanha steak over glowing charcoal" fill priority className="object-cover opacity-55" sizes="100vw" />
      <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(24,18,15,.95)_0%,rgba(45,20,17,.58)_53%,rgba(24,18,15,.24)_100%)]" />
      <header className="relative z-10 mx-auto flex max-w-[1440px] items-center justify-between px-6 py-6 md:px-12 lg:px-20"><Brand light /><nav className="hidden items-center gap-8 font-mono text-[10px] uppercase tracking-[0.2em] md:flex"><a href="#story" className="hover:text-primary">Our story</a><a href="https://pedir.delivery/app/oreidapicanha/menu" target="_blank" rel="noreferrer" className="hover:text-primary">The menu</a><a href="#visit" className="hover:text-primary">Find us</a></nav></header>
      <div className="relative z-10 mx-auto flex min-h-[78svh] max-w-[1440px] flex-col justify-end px-6 pb-12 md:px-12 md:pb-20 lg:px-20"><p className="section-kicker text-primary">Brazilian steakhouse · Philadelphia</p><h1 className="mt-5 max-w-5xl font-serif text-6xl uppercase leading-[0.82] tracking-[-0.045em] md:text-8xl lg:text-[8.5rem]">The art of<br />the perfect<br /><span className="text-primary">cut.</span></h1><div className="mt-10 flex items-end justify-between gap-8"><p className="max-w-sm text-sm leading-6 text-background/70">Authentic Brazilian barbecue, generous cuts and the warmth of a table made for gathering.</p><a href="#story" aria-label="Discover our story" className="flex size-12 items-center justify-center rounded-full border border-background/40 hover:border-primary hover:text-primary"><ArrowDown className="size-5" /></a></div></div>
    </section>

    <section id="story" className="bg-background px-6 py-20 md:px-12 lg:px-20 lg:py-32"><div className="mx-auto grid max-w-[1200px] gap-12 lg:grid-cols-[.8fr_1.2fr] lg:gap-24"><div><p className="section-kicker text-primary">A Brazilian tradition</p><h2 className="mt-5 max-w-lg font-serif text-5xl uppercase leading-[.9] tracking-[-.04em] md:text-7xl">Born from fire.<br />Made to share.</h2></div><div className="flex max-w-xl flex-col justify-end gap-8"><p className="text-xl leading-8 text-muted-foreground md:text-2xl">At The King of Picanha, every cut tells a story. We bring the spirit of Brazil to Philadelphia through fire, flavor and a table full of people you love.</p><div className="grid gap-6 border-t border-border pt-6 sm:grid-cols-2"><div><Flame className="size-5 text-primary" /><p className="mt-4 text-sm leading-6 text-muted-foreground">Open flame, patient hands and the unmistakable taste of churrasco.</p></div><div><Utensils className="size-5 text-primary" /><p className="mt-4 text-sm leading-6 text-muted-foreground">Classic Brazilian dishes prepared generously, meant to be passed around.</p></div></div></div></div></section>

    <section id="menu" className="grid bg-secondary md:grid-cols-2"><div className="relative min-h-[440px]"><Image src="/images/restaurant-interior.jpg" alt="Warm interior of The King of Picanha steakhouse" fill className="object-cover" sizes="(max-width: 768px) 100vw, 50vw" /></div><div className="flex flex-col justify-center px-6 py-16 md:px-12 lg:px-20"><p className="section-kicker text-primary">The experience</p><h2 className="mt-5 max-w-md font-serif text-5xl uppercase leading-[.9] tracking-[-.04em] md:text-6xl">Come hungry.<br />Leave happy.</h2><p className="mt-7 max-w-md leading-7 text-muted-foreground">Picanha, grilled specialties and Brazilian classics. Lunch, dinner or brunch — there is always room at our table.</p><a href="#visit" className="mt-9 flex w-fit items-center gap-3 border-b border-primary pb-2 font-mono text-xs uppercase tracking-[.18em] hover:text-primary">Explore the menu <ArrowUpRight className="size-4" /></a></div></section>

    <section id="order" className="bg-primary px-6 py-16 text-primary-foreground md:px-12 lg:px-20"><div className="mx-auto flex max-w-[1200px] flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="section-kicker text-primary-foreground/70">Online order</p><h2 className="mt-4 max-w-2xl font-serif text-5xl uppercase leading-[.9] tracking-[-.04em] md:text-7xl">Craving picanha now?</h2></div><a href="https://pedir.delivery/app/oreidapicanha/menu" target="_blank" rel="noreferrer" className="button-light w-fit border-primary-foreground/50">Order online <ArrowUpRight className="size-4" /></a></div></section>

    <LocationSection />
    <footer className="flex flex-col justify-between gap-6 border-t border-border px-6 py-8 md:flex-row md:items-center md:px-12 lg:px-20"><Brand /><div className="flex items-center gap-6"><a href="https://www.instagram.com/oreidapicanha_steak_house/" target="_blank" rel="noreferrer" aria-label="Instagram" className="font-mono text-[10px] uppercase tracking-[.18em] text-muted-foreground hover:text-primary">Instagram</a><p className="font-mono text-[10px] uppercase tracking-[.18em] text-muted-foreground">7534 Castor Ave · Philadelphia, PA</p></div><a href="#top" className="font-mono text-[10px] uppercase tracking-[.18em] text-muted-foreground hover:text-primary">Back to top ↑</a></footer>
  </main>
}
