'use client'

import { useEffect, useState } from 'react'
import { ArrowUpRight, Clock3, MapPin, Phone } from 'lucide-react'
import { formattedHours, getOpenStatus, getTodayHours } from '@/lib/business-hours'

const phone = '+1 (267) 343-7707'
const mapsUrl = 'https://www.google.com/maps/dir/?api=1&destination=The+King+of+Picanha+Steakhouse%2C+7534+Castor+Ave%2C+Philadelphia%2C+PA+19152'

export function LocationSection() {
  const [isOpen, setIsOpen] = useState(false)
  useEffect(() => { const update = () => setIsOpen(getOpenStatus()); update(); const timer = window.setInterval(update, 60000); return () => window.clearInterval(timer) }, [])
  const today = getTodayHours()
  return <section id="visit" className="border-t border-border bg-background px-6 py-20 md:px-12 lg:px-20 lg:py-28"><div className="mx-auto grid max-w-[1200px] gap-14 lg:grid-cols-[.85fr_1.15fr] lg:gap-20"><div className="flex flex-col justify-between gap-12"><div><p className="section-kicker text-primary">Visit the King</p><h2 className="mt-5 max-w-xl font-serif text-5xl uppercase leading-[.9] tracking-[-.04em] text-foreground md:text-7xl">Come experience<br />the King.</h2><p className="mt-7 max-w-md text-base leading-7 text-muted-foreground">The table is set in Philadelphia. Bring your appetite — we will take care of the fire.</p></div><div className="grid gap-7 border-t border-border pt-7 sm:grid-cols-2"><div><p className="meta-label"><MapPin className="size-4 text-primary" /> Find us</p><address className="mt-3 not-italic text-lg leading-7">7534 Castor Ave<br />Philadelphia, PA 19152</address></div><div><p className="meta-label"><Phone className="size-4 text-primary" /> Call us</p><a className="mt-3 inline-block text-lg underline decoration-primary/50 underline-offset-4 hover:text-primary" href="tel:+12673437707">{phone}</a></div></div><div className="flex flex-wrap gap-3"><a href={mapsUrl} target="_blank" rel="noreferrer" className="button-primary">Get directions <ArrowUpRight className="size-4" /></a><a href="tel:+12673437707" className="button-secondary">Call now</a></div></div><div className="grid gap-5"><div className="relative min-h-[310px] overflow-hidden bg-muted md:min-h-[380px]"><iframe title="Map to The King of Picanha Steakhouse" src="https://www.google.com/maps?q=The+King+of+Picanha+Steakhouse,+7534+Castor+Ave,+Philadelphia,+PA+19152&output=embed" className="absolute inset-0 size-full border-0 grayscale-[.35]" loading="lazy" /></div><div className="grid gap-5 border border-border p-6 md:grid-cols-[1fr_auto] md:p-8"><div><p className="meta-label"><Clock3 className="size-4 text-primary" /> Today&apos;s hours</p><p className="mt-3 text-lg">{today ? `${formatTime(today.open)} – ${formatTime(today.close)}` : 'Closed today'}</p></div><div className="flex items-center gap-2 md:self-start"><span className={`size-2 rounded-full ${isOpen ? 'bg-primary' : 'bg-muted-foreground'}`} /><span className="font-mono text-xs font-semibold uppercase tracking-[.18em]">{isOpen ? 'Open now' : 'Closed now'}</span></div></div><details className="border-b border-border pb-3"><summary className="cursor-pointer list-none font-mono text-xs uppercase tracking-[.18em] text-muted-foreground">See all hours</summary><div className="mt-5 grid gap-2 text-sm">{formattedHours.map(([day, hours]) => <div key={day} className="flex justify-between border-t border-border/60 py-2 text-muted-foreground"><span>{day}</span><span className="text-foreground">{hours}</span></div>)}</div></details></div></div></section>
}
function formatTime(time: string) { const [hour, minute] = time.split(':').map(Number); return `${hour % 12 || 12}:${String(minute).padStart(2, '0')} ${hour >= 12 ? 'PM' : 'AM'}` }
